# Generated by Django 6.0.6 on 2026-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_expiration',
            field=models.DateField(),
        ),
    ]
